name: ml-binp
channels:
  - defaults
  - conda-forge
  - plotly
  - pytorch
dependencies:
  - python=3.8
  - pip=20.1
  - pip:
    - shap==0.39
    - seaborn==0.11
#    - zfit
    - xgboost==1.4
    - npm
  - root=6.22
  - iminuit=2.4
  - mplhep=0.3
  - scikit-learn=0.24
  - scipy=1.6
  - statsmodels=0.12
  - plotly=4.14
  - pandas=1.2
  - numpy=1.20
  - lightgbm=3.2
  - catboost=0.25
  - matplotlib=3.4
  - jupyterlab=3.0
  - ipywidgets=7.5
  - tqdm=4.60
  - ipywidgets=7.5
  - cpuonly
  - tensorflow=2.4
  - pytorch=1.8
  - torchvision=0.9
  - hist=2.3
  - pyhf=0.6
  - awkward=1.2
  - uproot=4.0
